[package]
name = "fqlib"
version = "0.7.0"
authors = ["Michael Macias <michael.macias@stjude.org>"]
edition = "2018"
license = "Apache-2.0"
publish = false
autobins = false

[[bin]]
name = "fq"
path = "src/main.rs"

[profile.release]
lto = "fat"
codegen-units = 1

[dependencies]
anyhow = "1.0.31"
bbloom = { git = "https://github.com/zaeleus/bbloom.git", tag = "v0.1.0" }
clap = "2.31.2"
flate2 = "1.0.14"
git-testament = "0.1.6"
rand = { version = "0.8.1", features = ["small_rng"] }
rand_distr = { version = "0.4.0" }
tracing = "0.1.25"
tracing-subscriber = "0.2.16"
