name: CI

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: cargo fmt -- --check

  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: cargo clippy -- --deny warnings

  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: cargo test
